# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ivajo Blog
email: ivajodimo26@gmail.com
description: > # Blog personal, donde comento lo que se y comparto el contenido que genero.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ivajo.tk" # the base hostname & protocol for your site
twitter_username: ivajo26
github_username:  ivajo26

# Build settings
markdown: kramdown

paginate: 6

paginate_path: "/blog/:num/"

gems: [jekyll-paginate]
